--DROP TABLE StagingTAMEmployee
--DROP TABLE StagingDealerEmployee
--DROP TABLE StagingManpowerPositionType
--DROP TABLE StagingOutlet
--DROP TABLE StagingRegion
--DROP TABLE StagingSalesArea
--DROP TABLE StagingAfterSalesArea
--DROP TABLE StagingDealerGroup
--DROP TABLE StagingDealerCompany

CREATE TABLE StagingTAMEmployee (
	Code VARCHAR(250) NOT NULL PRIMARY KEY,
	Name VARCHAR(250) NOT NULL,
	Position VARCHAR(5) NOT NULL,
	State VARCHAR(250) NOT NULL,
)

CREATE TABLE StagingDealerEmployee (
	Code VARCHAR(250) NOT NULL PRIMARY KEY,
	Name VARCHAR(250) NOT NULL,
	OutletId DECIMAL(38, 0) NOT NULL,
	LastManpowerPositionTypeId VARCHAR(10) NOT NULL,
	ManpowerStatusTypeId VARCHAR(10) NULL,
	EmployeeId VARCHAR(50) NOT NULL,
	Phone VARCHAR(64) NULL,
	Email VARCHAR(255) NULL,
	State VARCHAR(250) NOT NULL,
)

CREATE TABLE StagingManpowerPositionType (
	Code VARCHAR(250) NOT NULL PRIMARY KEY,
	Name VARCHAR(250) NOT NULL,
	State VARCHAR(250) NOT NULL,
)

CREATE TABLE StagingOutlet (
	Code VARCHAR(250) NOT NULL PRIMARY KEY,
	Name VARCHAR(250) NOT NULL,
	DealerCompanyId DECIMAL(38, 0) NOT NULL,
	OutletFunctionId VARCHAR(5) NOT NULL,
	OutletCode VARCHAR(10) NOT NULL,
	PhoneNumber VARCHAR(64) NULL,
	KabupatenId DECIMAL(38, 0) NOT NULL,
	TamAreaId DECIMAL(38, 0) NOT NULL,
	TamAreaAfterSalesId DECIMAL(38, 0) NULL,
	State VARCHAR(250) NOT NULL,
)

CREATE TABLE StagingRegion (
	Code VARCHAR(250) NOT NULL PRIMARY KEY,
	ParentCode DECIMAL(38, 0) NULL,
	Name VARCHAR(250) NOT NULL,
	State VARCHAR(250) NOT NULL,
)

CREATE TABLE StagingSalesArea (
	Code VARCHAR(250) NOT NULL PRIMARY KEY,
	Name VARCHAR(250) NOT NULL,
	State VARCHAR(250) NOT NULL,
)

CREATE TABLE StagingAfterSalesArea (
	Code VARCHAR(250) NOT NULL PRIMARY KEY,
	Name VARCHAR(250) NOT NULL,
	State VARCHAR(250) NOT NULL,
)

CREATE TABLE StagingDealerGroup (
	Code VARCHAR(250) NOT NULL PRIMARY KEY,
	Name VARCHAR(250) NOT NULL,
	DealerGroupCode VARCHAR(3) NOT NULL,
	State VARCHAR(250) NOT NULL,
)

CREATE TABLE StagingDealerCompany (
	Code VARCHAR(250) NOT NULL PRIMARY KEY,
	Name VARCHAR(250) NOT NULL,
	DealerGroupId DECIMAL(38, 0) NOT NULL,
	State VARCHAR(250) NOT NULL,
)