DROP TABLE StagingTAMEmployee

CREATE TABLE StagingUser (
	ID INT NOT NULL,
	Code VARCHAR(250) NOT NULL
		CONSTRAINT PK_StagingUser PRIMARY KEY,
	Name VARCHAR(250) NOT NULL,
	NoReg VARCHAR(20) NOT NULL,
	Email VARCHAR(150) NULL,
	State VARCHAR(250) NOT NULL
)