--UNTUK MENGHAPUS CONSTRAINT ISPASSED DI TABLE ENROLLLEARNING.. 
--PASTIKAN UNTUK MENGGANTI CONSTRAINT NAME SESUAI DENGAN NAMA CONSTRAINTNYA (TIAP DATABASE BEDA BEDA)
ALTER TABLE [dbo].[EnrollLearnings] DROP CONSTRAINT [DF__EnrollLea__IsPas__16EE5E27]
GO

--MERUBAH KOLOM ISPASSED JADI NULLABLE
ALTER TABLE [dbo].[EnrollLearnings] ALTER COLUMN IsPassed BIT NULL
GO