ALTER TABLE ApprovalPositionMappings
ALTER COLUMN Description VARCHAR(MAX) NOT NULL

ALTER TABLE Assessments
ALTER COLUMN Description VARCHAR(MAX) NULL

ALTER TABLE Banners
ALTER COLUMN Description VARCHAR(MAX) NOT NULL

ALTER TABLE Competencies
ALTER COLUMN CompetencyDescription VARCHAR(MAX) NULL

ALTER TABLE Courses
ALTER COLUMN CourseDescription VARCHAR(MAX) NULL

ALTER TABLE Employees
ALTER COLUMN Description VARCHAR(MAX) NULL

ALTER TABLE EventCategories
ALTER COLUMN Description VARCHAR(MAX) NULL

ALTER TABLE Events
ALTER COLUMN Description VARCHAR(MAX) NULL

ALTER TABLE Guides
ALTER COLUMN Description VARCHAR(MAX) NOT NULL

ALTER TABLE Hobbies
ALTER COLUMN Description VARCHAR(MAX) NULL

ALTER TABLE KeyActions
ALTER COLUMN KeyActionDescription VARCHAR(MAX) NULL

ALTER TABLE Modules
ALTER COLUMN ModuleDescription VARCHAR(MAX) NOT NULL

ALTER TABLE News
ALTER COLUMN Description VARCHAR(MAX) NULL

ALTER TABLE Positions
ALTER COLUMN PositionDescription VARCHAR(MAX) NOT NULL

ALTER TABLE Rewards
ALTER COLUMN Description VARCHAR(MAX) NULL

ALTER TABLE Rewards
ALTER COLUMN TermsAndConditions VARCHAR(MAX) NOT NULL

ALTER TABLE Rewards
ALTER COLUMN HowToUse VARCHAR(MAX) NOT NULL

ALTER TABLE Roles
ALTER COLUMN Description VARCHAR(MAX) NULL

ALTER TABLE SurveySpecialAnswers
ALTER COLUMN Answer VARCHAR(MAX) NULL

ALTER TABLE TaskAnswerDetails
ALTER COLUMN Answer VARCHAR(MAX) NULL

ALTER TABLE TaskChecklistTypes
ALTER COLUMN Question VARCHAR(MAX) NOT NULL

ALTER TABLE TaskEssayTypes
ALTER COLUMN Question VARCHAR(MAX) NOT NULL

ALTER TABLE TaskFileUploadTypes
ALTER COLUMN Question VARCHAR(MAX) NOT NULL

ALTER TABLE TaskHotspotTypes
ALTER COLUMN Question VARCHAR(MAX) NOT NULL

ALTER TABLE TaskMatrixTypes
ALTER COLUMN Question VARCHAR(MAX) NOT NULL

ALTER TABLE TaskMultipleChoiceTypes
ALTER COLUMN Question VARCHAR(MAX) NOT NULL

ALTER TABLE TaskRatingTypes
ALTER COLUMN Question VARCHAR(MAX) NOT NULL

ALTER TABLE Tasks
ALTER COLUMN StoryLineDescription VARCHAR(MAX) NULL

ALTER TABLE TaskSequenceTypes
ALTER COLUMN Question VARCHAR(MAX) NOT NULL

ALTER TABLE TaskSpecialAnswers
ALTER COLUMN Answer VARCHAR(MAX) NULL

ALTER TABLE TaskTebakGambarTypes
ALTER COLUMN Question VARCHAR(MAX) NOT NULL

ALTER TABLE TaskTrueFalseTypes
ALTER COLUMN Question VARCHAR(MAX) NOT NULL

ALTER TABLE Topics
ALTER COLUMN TopicDescription VARCHAR(MAX) NULL

--2000
ALTER TABLE TaskChecklistChoices
ALTER COLUMN Text VARCHAR(2000) NOT NULL

ALTER TABLE TaskMatchingChoices
ALTER COLUMN Text VARCHAR(2000) NULL

ALTER TABLE TaskHotSpotAnswers
ALTER COLUMN Answer VARCHAR(2000) NOT NULL

ALTER TABLE TaskMatrixChoices
ALTER COLUMN Text VARCHAR(2000) NOT NULL

ALTER TABLE TaskMultipleChoiceChoices
ALTER COLUMN Text VARCHAR(2000) NOT NULL

ALTER TABLE TaskRatingChoices
ALTER COLUMN Text VARCHAR(2000) NOT NULL

ALTER TABLE TaskSequenceChoices
ALTER COLUMN Text VARCHAR(2000) NOT NULL